# Generated by Django 5.2 on 2025-05-12 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='file',
            field=models.FileField(blank=True, upload_to='materials/', verbose_name='Файл'),
        ),
    ]
